
package projectpp;
import java.awt.*;//BorderLayout y CardLayout estan aqui
import javax.swing.JPanel;
import java.util.List;
import java.util.Arrays;

public class Alaves extends javax.swing.JPanel {

    private Equipo alaves = new Equipo();
    
    public Alaves(Equipo alaves) {
        initComponents();
        this.alaves.establecernombre(alaves.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnEquipo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        BtnEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Alaves.png"))); // NOI18N
        BtnEquipo.setContentAreaFilled(false);
        BtnEquipo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Alaves.png"))); // NOI18N
        BtnEquipo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/AlavesClick.png"))); // NOI18N
        BtnEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BtnEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BtnEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEquipoActionPerformed
        Ranking  v2= new Ranking(alaves);
        v2.setVisible(true);
        this.setVisible(false);//checar pq no jala
        
    }//GEN-LAST:event_BtnEquipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEquipo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
